Fix 2d72d6876c52 migration failure with overdrive advantage collections (#1560)
20231101_2d72d6876c52_remove_collection_external_integration.py failed to properly account for Overdrive advantage collections, so the migration would fail with the following error:

pydantic.error_wrappers.ValidationError: 3 validation errors for OverdriveSettings
overdrive_website_id
  field required (type=value_error.missing)
overdrive_client_key
  field required (type=value_error.missing)
overdrive_client_secret
  field required (type=value_error.missing)