Fix TypeError in update_lane_size script (#1420)
Add default of None to _db arg for the update_lane_size script.

Fixes this traceback:
  File "bin/update_lane_size", line 11, in <module>
    UpdateLaneSizeScript().run()
TypeError: __init__() missing 1 required positional argument: '_db'