Fix bug looking up boundless datasource (PP-2758) (#2640)
The datasource lookup for collections was broken with a boundless
datasource, since the datasource name isn't equal to the collection
protocol.

I also added some additional logging as part of this PR that would have
made this easier to track down if it were to happen again.

This is probably causing us lots of issues with boundless collections,
but it is causing this issue in our patron activity sync task for sure:
```
Traceback (most recent call last):
  File "/var/www/circulation/env/lib/python3.10/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/circulation/env/lib/python3.10/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/circulation/src/palace/manager/celery/tasks/patron_activity.py", line 76, in sync_patron_activity
    api.sync_patron_activity(patron, pin)
  File "/var/www/circulation/src/palace/manager/api/circulation/base.py", line 351, in sync_patron_activity
    self.sync_loans(patron, remote_loans, local_loans)
  File "/var/www/circulation/src/palace/manager/api/circulation/base.py", line 325, in sync_loans
    loan.create_or_update(patron)
  File "/var/www/circulation/src/palace/manager/api/circulation/data.py", line 100, in create_or_update
    license_pool = license_pool or self.license_pool(session)
  File "/var/www/circulation/src/palace/manager/api/circulation/data.py", line 34, in license_pool
    pool, is_new = LicensePool.for_foreign_id(
  File "/var/www/circulation/src/palace/manager/sqlalchemy/model/licensing.py", line 433, in for_foreign_id
    data_source.primary_identifier_type
AttributeError: 'NoneType' object has no attribute 'primary_identifier_type'
```

- Tested locally
- Added new unit test

- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.